### PR TITLE
Merged other fork improvements and added statistics

### PR DESCRIPTION
**Pull request by aarontc**
Updated for modern Rake and Bundler compatibility as well.

### CODE REVIEW

**Comment by ninjudd** [comment]
Hey @aarontc. Thanks for the PR!

I'm not using method_cache in my day job anymore, so I'm happy to add you as a collaborator so you can merge changes. Long term, I'm also open to moving the repository if you're interesting in taking over as maintainer.

**Comment by ninjudd** [comment]
I just remembered that @stangel and @ss are probably still using method_cache, so they should probably chime in too 😬

**Comment by stangel** [comment]
No worries, @ninjudd -- we can always fork it if things go in a direction we can't accommodate.

**Comment by aarontc** [comment]
@ninjudd I'd be willing to discuss the idea with you - for the last year or so the state of my fork has been working for us, I'd have to jump back in and see what else we have that's different now.

**Comment by aarontc** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
